In [9]:
from flask import Flask,render_template, request, jsonify
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.multioutput import MultiOutputClassifier
from sintomas import categorias, sintomas, traduccion

print('Read train data...')

df = pd.read_csv("./dataset/Training.csv")
df.describe()
df.shape

df.drop('Unnamed: 133', axis=1, inplace=True)
df.columns

df['prognosis'].value_counts()

x = df.drop('prognosis', axis = 1)

# read Training2.csv
df2 = pd.read_csv("./dataset/TrainingY.csv")
y=df2

print('Read test data...')
dft = pd.read_csv("./dataset/Testing.csv")
dft.describe()
dft.shape

dft.columns

dft['prognosis'].value_counts()

xt = dft.drop('prognosis', axis = 1)
yt = dft['prognosis']

base_classifier = DecisionTreeClassifier()
multi_output_classifier = MultiOutputClassifier(base_classifier)

print('Training model...')
multi_output_classifier.fit(x, y)
print('Model trained!')

Read train data...
Read test data...
Training model...
Model trained!


In [14]:
multi_output_classifier.predict(xt.loc[[1]])
multi_output_classifier.predict_proba(xt.loc[[1]])

[array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[0., 1.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]]),
 array([[1., 0.]])]